version: '3.8'

services:
  gateway:
    build:
      context: ./infrastructure/centrifugo
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
      - "8060:8060"
    depends_on:
      - redis
    volumes:
      - ./infrastructure/centrifugo/config.json:/centrifugo/config.json
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
